name: "Pixiv Crawler"

on:
  schedule:
    - cron: '0 6 * * *'  
  push:
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  job_1:
    name: Python Crawler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main # 改成存放图片的分支
    #clear个锤子
    - name: Clear Previous
      run: |
        rm -f -- *.html
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1 
    - name: Install Dependence
      run: |
        pip install requests
        pip install pytest-shutil
        pip install imagesize
    - name: Run Bot
      run: python RunBot-Alpha.py
    - name: list
      run: ls - R
    - name: Upload to this repo
      run: |
        ls
        cat List.data
        git config --global user.name "Clancy6" # 改成Github账号用户名
        git config --global user.email "Clancy1921@outlook.com" # 改成GitHub账号的邮箱
        git add "*.html" && echo "Git Added" # 参考: https://stackoverflow.com/questions/25083290/git-add-error-unknown-switch
        git commit -m 'upload pa result' && echo "Git Committed"
        git push -u origin main && echo "Git Pushed Origin" # runner改成存放图片的分支
    - name: Failure test
      if: failure()
      run: | 
        ls
        echo "Error on running!"
